@host=localhost:7000
@imdbID=tt0417299
@season=3
@episode=1
@subtitleID=275026


GET http://{{host}}/{{imdbID}}/{{season}}/{{episode}}/{{subtitleID}}.srt


# Note: All possible errors in this route have been mitigated.